language: node_js
cache:
  directories:
  - node_modules
node_js:
 - "4"
 - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install: npm install -g grunt-cli bower
install:
 - npm install
 - bower install
before_script:
 - grunt build
 - chmod +x ./scripts/test_examples.sh
after_script: cat ./bin/coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js
deploy:
  - provider: releases
    api_key:
      secure: DNq1wbqLPHVpJPDx9O89HZM+RJB6v2R7/wk8pok7Z8NT72kUWdvbqcThGhczPO4sZ8cUTJ3ergTCE8hs9mynlR/lX6932U4fj4+uICQL9+G+deBB/t2SNyTBllkE64WrJ9BKmQvIk/Chh7ZJOM0Fro3p2BIq3JsVnfYg1tZ3U5o=
    file:
      - package/chevrotain-binaries-0.5.11.zip
      - package/chevrotain-binaries-0.5.11.tar.gz
    on:
      tags : true
      all_branches: true
    skip_cleanup: true

  - provider: npm
    email: shahar.soel@gmail.com
    api_key:
      secure: k7juzhofg3lWLolMOIQ6AM0xKYLaRc0MAlGO3sbm2ZFZlGdmXuayHGAD+UL1Vi+KXLfU14fwvIjCpkWc6EWezcFkTG2cxoIC+NpUygQ0z3/E1ylCYM5NU23J+bDtv9xcj5bhNQ/611kHahtIH9DNbY1BbsL0lMH6KwbLDXYUlzk=
    on:
      tags: true
      all_branches: true
    skip_cleanup: true
