language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "0.12"
before_install: npm install -g grunt-cli bower
install: npm install
before_script: grunt build
after_script: cat ./bin/coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js